#theme: jekyll-theme-minimal
title: CET Graduation Day 2023 - Seat Arrangement
description: CET Graduation Day 2023 - Seat Arrangement
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
